name: Cypress Qazando Tests
on:
    pull_request:
        branches: [ main ]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            # Clone do repositório
            - name: Checkout
              uses: actions/checkout@v4

            # rodar os testes
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                record: true
              env: 
                CYPRESS_RECORD_KEY: 02f68566-dbd5-44a9-b32c-45f490ff3a4a